<div class="panel-body box-bg">
<div class="bs-docs-section well">
  <h1>Our  Cookie Policy</h1>
  <h4>Our  Statement of Cookie Compliance</h4>
  <h4>London4arabs.com uses cookies</h4>
  <p>Whenever  you use London4arabs.com - be that over a web browser on a PC or via a smart  phone, it is a better experience if users allow information about what the user  does on the site (such as the pages they visit, their search preferences and  products they select) to be collected through the use of cookies and similar  technologies.</p>
  <p><strong>By using  London4arabs.com you have the option to accept or decline to our use of cookies  as described in this Cookie Policy. However to take advantage of the full range  of services on London4arabs.com you do need to allow cookies to remain turned  on.</strong></p>
  <h4>What are 'Cookies'?</h4>
  <p>Cookies  are small text files which are downloaded to your computer or mobile device  when you visit a website or application. Your web browser (such as Internet  Explorer, Firefox or Google Chrome) then sends these cookies back to the  website or application on each subsequent visit so that they can recognise you  and remember things like personalised details or user preferences.</p>
  <p>Cookies  are very useful and do lots of different jobs which help to make your  experience on websites as smooth as possible. For example, they let you move  between web pages efficiently, remembering your preferences, and generally  improving your experience. They can also help to ensure that adverts you see  online are more relevant to you and your interests.</p>
  <p>They are  referred to as&nbsp;<strong>session</strong>&nbsp;or&nbsp;<strong>persistent</strong>&nbsp;cookies,  depending on how long they are used:</p>
  <p><strong>&nbsp; • </strong>Session cookies only last for your online session and disappear  from your computer or device when you close your browser.<strong></strong></p>
  <p><strong>&nbsp; • </strong>Persistent cookies stay on your computer or device after the  browser has been closed and last for the period of time specified in the  cookie. These persistent cookies are activated each time you visit the site  where the cookie was generated.<strong></strong></p>
  <p>Which cookies does London4arabs.com use and  why?</p>
  <p>When you  use London4arabs.com, the following 5 categories of cookies may be set on your  device:</p>
  <h4><strong>1.  'Strictly necessary' cookie</strong></h4>
  <p>These  cookies are essential in helping you to move around our websites and use  features such as hotel booking and accessing secure areas of the website.  Without these cookies, services you may want to use, such as completing  complicated forms on London4arabs.com, cannot be provided. These cookies do not  gather information about you that could be used for marketing or remembering  where you've been on the internet.</p>
  <p>Some  examples of these essential cookies include:</p>
  <p><strong>&nbsp; • </strong>Remembering previous actions (such as text you've entered in a  registration form) when navigating back to a page in the same session.<strong></strong></p>
  <p><strong>&nbsp; • </strong>Identifying you as being signed in to London4arabs.com and our  other websites and keeping you logged in throughout your visit so that you  don't need to sign in each and every time you visit.<strong></strong></p>
  <p><strong>&nbsp; • </strong>Remembering security settings, such as what level of access you  may have to a 'members' area of the site which has restricted access to certain  content.<strong></strong></p>
  <p><strong>&nbsp; • </strong>Remembering the dates of your trip when you are navigating the  hotel search service.<strong></strong></p>
  <h4><strong>2.  Functional cookies</strong></h4>
  <p>These  cookies allow websites and applications to remember choices you make (such as  your user name, language or the region you are in) and provide enhanced, more  personal features. The information these cookies collect is usually  'anonymised' - which means we&nbsp;<strong>can't identify you personally</strong>. They  do not gather any information about you that could be used for selling  advertising or remembering where you've been on the internet.</p>
  <p>We use  these types of cookies to improve your experience on our website. Some examples  of how we try to do this may include:</p>
  <p><strong>&nbsp; • </strong>Remembering your preferences and settings. This might include  drop down menu selections, form input, disability settings (such as text sizes  and colours).<strong></strong></p>
  <p><strong>&nbsp; • </strong>Remembering if we've already asked you if you want to fill in a  survey or if you've completed a survey, so you're not asked to do it again.<strong></strong></p>
  <p><strong>&nbsp; • </strong>Remembering if you've been to the site before so that messages  intended for first-time users are not displayed to you.<strong></strong></p>
  <p><strong>&nbsp; • </strong>Remembering when you've voted in a poll or rated a product or  article so that you don't do this more than once during your visit.<strong></strong></p>
  <p><strong>&nbsp; • </strong>Supporting social media components, like Facebook or Twitter  (where a website uses a plugin from these third party platforms, for example).<strong></strong></p>
  <p>If you  would like a list of the functional cookies used by London4arabs.com or have  any further questions, you can use the form on our &lsquo;Contact us' page.</p>
  <h4><strong>3.  Analytics cookies</strong></h4>
  <p>In order  to keep London4arabs.com relevant, easy to use and up-to-date, we use web  analytics services to help us understand how people use them. For example, we  can see which parts of the website are most popular, identify which pages are  more relevant, identify when errors occur and test different versions of a page  or feature to see which one works best.</p>
  <p>These  web analytics services may be designed and operated by other companies on our  behalf. E.g Google Analytics. They do this using small invisible images such as  &quot;tracking pixels&quot; that may be included in the website. These are used  to count the number of times something has been seen. These web beacons are  anonymous and&nbsp;<strong>do not contain or collect any information that identifies  you</strong>.</p>
  <p>The web  analytics services may also use cookies and similar technologies to make the  information collected by the web beacons more useful. When you are viewing a  website, a cookie is transferred to your browser by the web server and is  stored on your computer. It can only be read by the server that gave it to you.</p>
  <p>Cookies  allow web analytics services to recognise your browser or device and, for  example, identify whether you have visited our website before, what you have  previously viewed or clicked on, and how you found us. The information is  anonymous and only used for statistical purposes. It allows us to track  information, such as how many individual users we have and how often they visit  our websites. It also helps us to analyse patterns of user activity and to  develop a better user experience. For example, we might see that many people  who viewed Page A also viewed Page B and we can then recommend Page B to  everyone else who viewed Page A.</p>
  <p>Web  analytics data and cookies cannot be used to identify you as they&nbsp;<strong>never</strong>&nbsp;contain  personal information such as your name or email address. However, if you have  registered and signed in to our website, we may combine information from your  registration with the data we get from the web analytics service and its  cookies (or similar technologies) to analyse how you and other people use our  website in detail and, where you have opted in to receive such communications,  to send you email and other communications that might be of interest to you.  The combined information may include information that is collected by the web  analytics services while you are not signed in, and information that was  collected using cookies and similar technologies before you registered or  signed in. Where the combined information can be used to identify you, we use  it only in accordance with our Terms of Use and Privacy Policy.</p>
  <h4><strong>4.  Targeting cookies</strong></h4>
  <p>We may  use cookies to assist in targeted advertising. This includes:</p>
  <p><strong>&nbsp; • </strong>Personalised retargeting is another form of OBA that enables  advertiser partners to show you adverts based on your online browsing away from  their websites. For example, if you visited the website of an online travel  company you may start seeing adverts from the same travel company displaying  special offers or showing you the products that you were browsing when you come  to a different websites. This allows companies to advertise to people who  previously visited their website. These cookies will usually be dropped by  third-party advertising networks, such as Criteo, Rubicon and Vibrant Media.<strong></strong></p>
  <p>&nbsp;Although these cookies can  track your visits around the web they don't know who you are. </p>
  <h4><strong>5. Other  third party cookies</strong></h4>
  <p>Please  note that on some pages of our websites you may notice that cookies have been  set that are not related to LondonTown.com or our authorised service providers.  When you visit a page with content embedded from, for example, YouTube or  Facebook, these service providers may set their own cookies on your web  browser. We only include third party providers who are trusted and well known  to the public - such as Google, Yahoo, Wow, You Tube, Facebook, LinkedIN etc.  These anonymous cookies may be set by that third party to track the success of  their application or to customise their application to you. London4arabs.com  does not control the use of these cookies and cannot access them due to the way  that cookies work, as cookies can only be accessed by the party who originally  set them. You should check the third party websites for more information about  these cookies.</p>
  <h4>How to control your cookies</h4>
  <p>Please  remember that London4arabs.com does not use cookies to collect personally  identifiable information about you although, as explained above, we may combine  information from your registration with the data we get from the web analytics  services we use and their cookies (or similar technologies) to analyse how you  and other people use our website in detail. These cookies are set to improve  your experience on our websites and to enable you to benefit from specific  features and to set preferences.</p>
  <p>However,  there are various ways that you can control and manage your cookies which are  discussed in a bit more detail below.&nbsp;<strong>Please remember that any settings  you change will not just affect London4arabs.com cookies. These changes will  apply to all websites that you visit (unless you choose to block cookies from  particular sites)</strong>.</p>
  <p>&nbsp;</p>
  <p>Managing cookies in your browser</p>
  <p>Most modern  browsers will allow you to:</p>
  <p><strong>&nbsp; • </strong>See what cookies you've got and delete them on an individual  basis.<strong></strong></p>
  <p><strong>&nbsp; • </strong>Block third party cookies.<strong></strong></p>
  <p><strong>&nbsp; • </strong>Block cookies from particular sites.<strong></strong></p>
  <p><strong>&nbsp; • </strong>Block all cookies from being set.<strong></strong></p>
  <p><strong>&nbsp; • </strong>Delete all cookies when you close your browser.<strong></strong></p>
  <p>You  should be aware that any preferences will be lost if you delete cookies.  Ironically, this includes where you have opted out from cookies, as this  requires an opt-out cookie to be set. Also, if you block cookies completely  many websites will not work properly and some functionality on these websites  will not work at all. We do not recommend turning cookies off when using our  website for these reasons.</p>
  <p>The  links below take you to the &lsquo;Help' sections for each of the major browsers so  that you can find out more about how to manage your cookies.</p>
  <p><strong>&nbsp; • </strong><a href="http://support.microsoft.com/kb/196955" target="_blank">Internet  Explorer</a><strong></strong><br />
    <strong>&nbsp; • </strong><a href="http://support.mozilla.org/en-US/kb/Cookies" target="_blank">Firefox</a>&nbsp;<strong> </strong><br />
    <strong>&nbsp; • </strong><a href="http://support.google.com/chrome/bin/answer.py?hl=en&amp;answer=95647" target="_blank">Google Chrome</a><strong></strong><br />
    <strong>&nbsp; • </strong><a href="http://www.opera.com/browser/tutorials/security/privacy/" target="_blank">Opera</a><strong></strong><br />
    <strong>&nbsp; • </strong><a href="http://support.apple.com/kb/PH11882" target="_blank">Safari</a><strong></strong><br />
    <strong>&nbsp; • </strong><a href="http://support.apple.com/kb/HT1677" target="_blank">Safari iOS</a><strong></strong><br />
    <strong>&nbsp; • </strong><a href="http://support.google.com/android/bin/answer.py?hl=en&amp;answer=1722193" target="_blank">Android</a><strong></strong><br />
    <strong>&nbsp; • </strong><a href="http://docs.blackberry.com/en/smartphone_users/deliverables/32004/Turn_off_cookies_in_the_browser_60_1072866_11.jsp" target="_blank">Blackberry</a><strong></strong><br />
    <strong>&nbsp; • </strong><a href="http://www.microsoft.com/windowsphone/en-us/howto/wp7/web/changing-privacy-and-other-browser-settings.aspx" target="_blank">Windows Phone</a><strong></strong></p>
</div>
    </div>